### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Substance12** [Substance12/PicroxxNew#1]
- [ ] Smooth transitions between gamestates

- [ ] Make the QR code reader actually read levels

- [ ] Level editor that exports to JSON format and generates QR codes with the compressed JSON

- [ ] Make the in-game state fully functional (reference marks, animations, pause menu and top screen needed)

- [ ] Fully implement 10x10 and 15x15 levels

- [ ] Implement Free Mode

- [ ] Convert all the .lua levels to JSON (write a script?)

- [ ] .3ds compiling (optional?)

- [ ] Fully functional main menu and it's submenus

- [ ] Make a proper banner

**Comment by Jinnial** [comment]
Nice! I look forward to seeing how this new clone pans out!

**Comment by Substance12** [comment]
QR CODE READERS ARE. NOT. FUN.

**Comment by Jinnial** [comment]
Yeah.....I can only imagine the stress and confusion behind actually getting them working.
